name: attest-single-file

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'README.md'
      - '.github/workflows/attest-single-file.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Attest
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4
        id: attest
        with:
          subject-path: ./README.md
