name: attest-single-file

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'README.md'
      - '.github/workflows/attest-single-file.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Attest
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4
        id: attest
        with:
          subject-path: ./README.md
