name: context

on:
  workflow_dispatch:
  issues: 
    types: [opened, edited]
  pull_request:
    paths:
      - '.github/workflows/context.yml'

permissions:
  issues: read

env:
  item1: item1value
  ITEM2: item2value

jobs:
  context:
    environment: context
    env:
      item3: item1value
      ITEM4: item2value
    runs-on: ubuntu-slim
    steps:
    - run: env | sort
    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
      with:
        script: |
          console.log(context)
