name: issues-test

on:
  issues:
    types: [labeled, edited]

permissions: {}

jobs:
  # use github-script to output the github context
  output:
    runs-on: ubuntu-slim
    steps:
    - name: output
      run: |
        echo ${{ toJSON(github) }}
    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
      with:
        script: |
          console.log(github.context)
